name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-2019

    env:
      Solution_Name: jbplugin.sln
      Test_Project_Path: jbplugin\jbplugin.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build the application
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Create installer
      uses: joncloud/makensis-action@v3.7
      with:
        arguments: "/V3"
        script-file: Setup\JBPlugin.nsi

    - name: Deploy 1
      run: |
        mkdir "${{ github.workspace }}/Rel/"
        copy "${{ github.workspace }}/Setup/Setup.exe" "${{ github.workspace }}/Rel/Setup.exe"

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Rel
        force_orphan: true
